Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,7 +14,35 @@ defaults:
     shell: bash
 
 jobs:
-  build:
+
+  fix-srcinfo-and-sums:
+    name: Push fixed .SRCINFO and update pkgbuild checksums
+    runs-on: ubuntu-latest
+    container: archlinux:base-devel
+    steps:
+      - uses: actions/checkout@v4
+      # makepkg fails even for printsrcinfo if uid==0 or if the src dir isn't writable.
+      - name: Create build user
+        run: |
+          useradd -m user
+          echo 'user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
+      - name: Chown repo to build user
+        run: chown --recursive user .
+      - name: Regenerate .SRCINFO
+        run: |
+          sudo -u user makepkg --printsrcinfo > .SRCINFO
+      - name: Fix pkgbuild checksums
+        run: sudo -u user updpkgsums
+      - name: Commit and push
+        run: |
+          git status || exit 0
+          git commit -a -m "bot chore: update .SRCINFO and pkgbuild sums" \
+            --author "GitHub Actions runner <null@bot>"
+          git push
+
+  makepkg:
+    name: Build Arch packages
+    needs: fix-srcinfo-and-sums
     permissions:
       contents: write
     runs-on: ubuntu-latest
@@ -36,14 +64,7 @@ jobs:
       - name: Ensure .SRCINFO isn't stale
         run: |
           sudo -u user makepkg --printsrcinfo > /tmp/.SRCINFO
-          diff .SRCINFO /tmp/.SRCINFO | tee /tmp/.SRCINFO.patch
-
-      - name: (fail) Save .SRCINFO diff
-        if: ${{ failure() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: required-patches
-          path: /tmp/.SRCINFO.patch
+          diff .SRCINFO /tmp/.SRCINFO
 
       - name: Get upstream PGP keys
         # this is very sensitive to choice of keyserver per key.
