Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,10 +12,6 @@ defaults:
   run:
     # required to get `-eo pipefail`
     shell: bash
-env:
-  # even git STATUS fails without these!
-  GIT_AUTHOR_NAME: GitHub Actions
-  GIT_AUTHOR_EMAIL: null@bot
 
 jobs:
   fix-srcinfo-and-sums:
@@ -52,8 +48,10 @@ jobs:
         run: git config --global --add safe.directory "$(realpath .)"
       - name: Commit and push
         run: |
-          echo lol this sucks $GIT_AUTHOR_NAME $GIT_AUTHOR_EMAIL
-          git status || exit 0
+          # even git STATUS fails without name and email! and it will not read the GIT_AUTHOR* vars! sucks!
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "null@bot"
+          git diff || exit 0
           git commit -a -m "bot chore: update .SRCINFO and pkgbuild sums"
           git push
 
