automerge merge-base --is-ancestor

diff --git a/.github/workflows/upstream-pr-bot.yml b/.github/workflows/upstream-pr-bot.yml
--- a/.github/workflows/upstream-pr-bot.yml
+++ b/.github/workflows/upstream-pr-bot.yml
@@ -27,30 +27,41 @@ jobs:
       - name: Read upstream repo
         run: |
           git fetch "$UPSTREAM_REMOTE" "$UPSTREAM_REF"
-          echo "Local rev:    $(git rev-parse HEAD)"
-          echo "Upstream rev: $(git rev-parse FETCH_HEAD)"
+          echo "Local (HEAD):          $(git rev-parse HEAD)"
+          echo "Upstream (FETCH_HEAD): $(git rev-parse FETCH_HEAD)"
+          # tricky to run the cmd, pass through any output, but also capture and switch on $? without overwriting it,
+          # AND hide nonzero cmd statuses from the outer shell so it can't kill the whole script.
+          if git merge-base --is-ancestor FETCH_HEAD HEAD ; then
+            export UP_TO_DATE=y
+          else
+            export ERR=$?
+            case $ERR in
+              1) export UP_TO_DATE= ;;
+              *) echo Up-to-date check git exitcode $ERR; exit $ERR ;;
+            esac
+          fi
+          echo "Up to date: $([ -n $UP_TO_DATE ] && echo yes || echo no)"
+          echo "UP_TO_DATE=$UP_TO_DATE" >> "$GITHUB_ENV"
       - name: Attempt automerge
+        if: ${{ env.UP_TO_DATE != 'y' }}
         # this automerge commit will 100% have wrong content in the pkgbuild, e.g. ignoring anything related to the new version number!
         # user just has to know that a commit (maybe amend) is needed. how can this be automated?
         # TODO learn gh actions job state and outputs and stuff...
         run: |
-          if [ -n "$(git branch --list "$(git branch --show-current)" --no-contains FETCH_HEAD)" ]; then
-            # ^ docs are confusing, but via experimentation --contains works, --merged doesn't.
-            git checkout -b "$BRANCH_NAME"  # --track is insane; will assoc to origin/main, not origin/BRANCH_NAME
-            # even with --no-commit, git merge will unalive itself without user name set.
-            git config user.name upstream-pr-bot
-            git config user.email upstream-pr@bot
-            # git merge with a normal strategy still exits with code 1 on conflicts, which can still
-            # happen on .SRCINFO sometimes because of the current not-so-great
-            # "build job commits .SRCINFO and PKGBUILD" setup.
-            # trial and error suggests git is good about reserving different exit codes for different things,
-            # so will keep going even with a code 1 fail here. still not great, but don't know what else to do.
-            git merge --no-commit -s ort -X ours FETCH_HEAD || [ $? -eq 1 ]
-            ./automerge-steps.sh
-            #git merge --continue
-            # ^ dies due to "dumb terminal, please use -m", but with --continue it straight up refuses to parse any other cli args and dies.
-            # --no-edit on the merge does not help. so, back to plain commit with a -m message.
-            git commit -m "merge $(git rev-parse FETCH_HEAD) from $UPSTREAM_REMOTE"
-            git push -u origin "$BRANCH_NAME"
-            gh pr create --draft --fill --body "Please fix this bad automerge and then bring it into main\!"
-          fi
+          git checkout -b "$BRANCH_NAME"  # --track is insane; will assoc to origin/main, not origin/BRANCH_NAME
+          # even with --no-commit, git merge will unalive itself without user name set.
+          git config user.name upstream-pr-bot
+          git config user.email upstream-pr@bot
+          # git merge with a normal strategy still exits with code 1 on conflicts, which can still
+          # happen on .SRCINFO sometimes because of the current not-so-great
+          # "build job commits .SRCINFO and PKGBUILD" setup.
+          # trial and error suggests git is good about reserving different exit codes for different things,
+          # so will keep going even with a code 1 fail here. still not great, but don't know what else to do.
+          git merge --no-commit -s ort -X ours FETCH_HEAD || [ $? -eq 1 ]
+          ./automerge-steps.sh
+          #git merge --continue
+          # ^ dies due to "dumb terminal, please use -m", but with --continue it straight up refuses to parse any other cli args and dies.
+          # --no-edit on the merge does not help. so, back to plain commit with a -m message.
+          git commit -m "merge $(git rev-parse FETCH_HEAD) from $UPSTREAM_REMOTE"
+          git push -u origin "$BRANCH_NAME"
+          gh pr create --draft --fill --body "Please fix this bad automerge and then bring it into main\!"
